# -*- coding: utf-8 -*-
"""Weather_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeTdCBvtpwda9f0PGjwiR7w7GB7_3sUD
"""

import streamlit as st
import requests
import matplotlib.pyplot as plt

# 페이지 기본 설정
st.set_page_config(page_title="Open-Meteo Weather App", page_icon="🌦️", layout="centered")

st.title("🌦️ Open-Meteo 실시간 날씨 앱")
st.caption("API 키 없이 전 세계 실시간 날씨 데이터 가져오기 🌍")

# 🔹 도시 선택
city = st.selectbox(
    "도시를 선택하세요",
    ["Seoul", "Busan", "Tokyo", "New York", "London"]
)

# 🔹 각 도시의 위도/경도 (Open-Meteo는 좌표 기반)
locations = {
    "Seoul": {"lat": 37.5665, "lon": 126.9780},
    "Busan": {"lat": 35.1796, "lon": 129.0756},
    "Tokyo": {"lat": 35.6764, "lon": 139.6500},
    "New York": {"lat": 40.7128, "lon": -74.0060},
    "London": {"lat": 51.5072, "lon": -0.1276}
}

# 🔹 선택한 도시 좌표
lat = locations[city]["lat"]
lon = locations[city]["lon"]

# 🔹 Open-Meteo API URL
url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"

# 🔹 버튼 눌렀을 때 실행
if st.button("날씨 불러오기"):
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        current = data["current_weather"]

        temp = current["temperature"]
        windspeed = current["windspeed"]
        weather_code = current["weathercode"]

        # 날씨 코드 참고표 간단 매핑
        weather_map = {
            0: "맑음 ☀️",
            1: "대체로 맑음 🌤",
            2: "약간 구름 ☁️",
            3: "흐림 ☁️☁️",
            45: "안개 🌫",
            48: "안개 🌫",
            51: "약한 비 🌦",
            61: "비 ☔️",
            71: "눈 ❄️",
        }

        weather_desc = weather_map.get(weather_code, "기타")

        st.subheader(f"📍 {city}의 현재 날씨")
        st.metric("기온 (°C)", f"{temp}°C")
        st.metric("풍속 (m/s)", windspeed)
        st.write(f"날씨 상태: {weather_desc}")

        # 시각화 (기온 & 풍속)
        fig, ax = plt.subplots()
        ax.bar(["Temperature", "Windspeed"], [temp, windspeed], color=["#FFB6C1", "#87CEFA"])
        ax.set_title(f"Weather Data - {city}")
        st.pyplot(fig)

    else:
        st.error(f"❌ 요청 실패: {response.status_code}")