# -*- coding: utf-8 -*-
"""Weather_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeTdCBvtpwda9f0PGjwiR7w7GB7_3sUD
"""

import streamlit as st
import requests
import matplotlib.pyplot as plt

# 🌤 앱 기본 설정
st.set_page_config(page_title="Weather API App", page_icon="🌦️", layout="centered")

st.title("🌦️ 실시간 날씨 Open API 앱")
st.caption("Powered by OpenWeather API")

# 🔹 도시 입력
city = st.text_input("도시 이름을 입력하세요 (예: Seoul, Busan, Tokyo)", "Seoul")

# 🔹 API 키 입력
st.info("⚙️ OpenWeather에서 API 키를 발급받아 입력해야 합니다.")
API_KEY = st.text_input("API Key 입력", type="password")

# 🔹 버튼 클릭 시 실행
if st.button("날씨 불러오기"):
    if not API_KEY:
        st.error("❌ API 키를 입력해주세요.")
    else:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()
            temp = data['main']['temp']
            feels_like = data['main']['feels_like']
            humidity = data['main']['humidity']
            weather = data['weather'][0]['description']