# -*- coding: utf-8 -*-
"""Weather_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeTdCBvtpwda9f0PGjwiR7w7GB7_3sUD
"""

import streamlit as st
import requests
import matplotlib.pyplot as plt

# 🌤 앱 기본 설정
st.set_page_config(page_title="Weather API App", page_icon="🌦️", layout="centered")

st.title("🌦️ 실시간 날씨 Open API 앱")
st.caption("Powered by OpenWeather API")

# 🔹 도시 입력
city = st.text_input("도시 이름을 입력하세요 (예: Seoul, Busan, Tokyo)", "Seoul")

# 🔹 API 키 직접 입력 (선재의 키 포함)
API_KEY = "8c6f2cd4a90213d6649576e1c83e06f3"

# 🔹 버튼 클릭 시 실행
if st.button("날씨 불러오기"):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        temp = data['main']['temp']
        feels_like = data['main']['feels_like']
        humidity = data['main']['humidity']
        weather = data['weather'][0]['description']
        icon = data['weather'][0]['icon']

        # 결과 표시
        st.subheader(f"📍 {city}의 날씨 정보")
        st.image(f"http://openweathermap.org/img/wn/{icon}@2x.png")
        st.metric(label="기온 (°C)", value=f"{temp:.1f}")
        st.metric(label="체감온도 (°C)", value=f"{feels_like:.1f}")
        st.metric(label="습도 (%)", value=f"{humidity}")

        # 그래프 시각화
        st.subheader("🌡 기온 및 습도 비교")
        fig, ax = plt.subplots()
        ax.bar(['Temperature', 'Feels Like', 'Humidity'],
               [temp, feels_like, humidity],
               color=['#FFB6C1', '#87CEFA', '#98FB98'])
        ax.set_ylabel("Value")
        ax.set_title(f"Weather Data for {city}")
        st.pyplot(fig)

    else:
        st.error(f"❌ 데이터를 불러오지 못했습니다. (Error code: {response.status_code})")
        st.write("🔍 상태 코드:", response.status_code)
        st.write("🧾 응답 내용:", response.text)